project:
  type: website
  output-dir: docs


website:
  title: "Home"
  
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/shreyasharathi
      - icon: linkedin
        href: www.linkedin.com/in/shreyasharathi
format:
  html:
    theme: default
    css: styles.css
    
    



