---
title: "Salary Patterns"
author: "Shreyas Harathi"
date: "2023-12-04"
categories: [linear regression, analysis]
---

**Linear Regression**

**Introduction**

In this blog post, we'll look into a salary dataset and employ linear regression to understand the relationship between years of experience and salary. Linear regression in machine learning is a supervised learning algorithm used for predicting a continuous outcome variable based on one or more input features. It establishes a linear relationship between the input features and the target variable by finding the best-fitting line through the data points.

**Exploring the Dataset**

Our dataset contains 30 entries of our two variables, Years of experience and Salary. Let's load the dataset.
```{python}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
```
```{python}
df=pd.read_csv('Salary_dataset.csv')
df.head()
```

```{python}
df.shape
```
```{python}
df.info()
```

We'll clean our data by dropping unnecessary columns and checking for missing or duplicated values.

```{python}
df.drop('Unnamed: 0',axis=1,inplace=True)
```
```{python}
# Check for Null values
df.isna().sum()
```

```{python}
# Check for Duplicated values
df.duplicated().sum()
```
```{python}
df.corr()
```

**EDA**

To gain insights into the dataset, we'll compute correlations and create visualizations, such as pair plots and scatter plots.
```{python}
sns.set(font_scale=2)
sns.pairplot(df, height=8, aspect=10/8)
```
```{python}
x=df['YearsExperience']
y=df['Salary']
```
```{python}
plt.rcParams["figure.figsize"] = (10, 8)
plt.scatter(x, y)
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.title("Salary with Years of Experience")
plt.grid(True)
plt.show()
x = np.array(x).reshape(-1, 1)
y = np.array(y).reshape(-1, 1)
```

**Train Test Split**

```{python}
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15)
```

**Linear Regression Model**

```{python}
lr=LinearRegression()
lr.fit(x_train,y_train)
```

**Predictions of our Model**

```{python}
y_preds=lr.predict(x_test)
print(y_preds)
```
```{python}
plt.rcParams["figure.figsize"] = (10, 8)
plt.scatter(x, y)
plt.xlabel("Years of Experience")
plt.ylabel("Salary")
plt.plot(x_test, y_preds, color = "r", label = "Regression line")
plt.title("Salary with Years of Experience")
plt.grid(True)
plt.legend()
plt.show()
```

**Model Evaluation**

```{python}
print("Mean Absolute Error = ", str(mean_absolute_error(y_test, y_preds)))
print("Mean Squared Error = ", str(mean_squared_error(y_test, y_preds)))
print("R-squared = ", str(r2_score(y_test, y_preds)))
```

**Conclusion**

In conclusion, our exploration into the salary dataset using linear regression has provided valuable insights into the relationship between years of experience and salary.